name = "tessera-web"
compatibility_date = "2024-12-01"
pages_build_output_dir = "out"

[env.production]
name = "tessera-web"
compatibility_date = "2024-12-01"

[env.preview]
name = "tessera-web-preview"
compatibility_date = "2024-12-01"

[[env.production.kv_namespaces]]
binding = "TESSERA_KV"
id = "your-kv-namespace-id-here"

[[env.preview.kv_namespaces]]
binding = "TESSERA_KV"
id = "your-preview-kv-namespace-id-here"
